### ISSUE TITLE
Reload funzt nach Update nicht

### ISSUE THREAD

**Issue by hinzke** [markocupic/contao-news-infinite-scroll-bundle#8]
Nach Update auf 1.3 funktioniert der reload nicht mehr.

Die veränderte j_news_infinite_scroll.html5 habe ich ausgetauscht und als einzige Änderung "loadMoreButton" auf "false" gesetzt. Oder muss man noch was beachten?

**Comment by markocupic** [comment]
Sollte eigentlich laufen. Hast du irgendwelche Fehler auf der Browserkonsole?

Kann man das irgendwo sehen?

**Comment by markocupic** [comment]
Die Pagination Einstellung im Template enthielt noch einen Fehler.
https://github.com/markocupic/contao-news-infinite-scroll-bundle/blob/8ad445a1769df4f7a5b003c053653c71b8e5652f/src/Resources/contao/templates/jquery/j_news_infinite_scroll.html5#L15-L18

Fixed in 8ad445a1769df4f7a5b003c053653c71b8e5652f

Gehe auf Version 1.3.1

**Comment by hinzke** [comment]
Super, das war die Lösung. Danke
